export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGIN_REFRESH_TOKEN_REQUEST = 'LOGIN_REFRESH_TOKEN_REQUEST'
export const LOGIN_REFRESH_TOKEN_SUCCESS = 'LOGIN_REFRESH_TOKEN_SUCCESS'
export const LOGIN_REFRESH_TOKEN_FAILED = 'LOGIN_REFRESH_TOKEN_FAILED'